[package]
name = "vm-bandwidth"
version.workspace = true
edition.workspace = true

[dependencies]
aya = "0.14"
vm-bandwidth-common = { path = "../vm-bandwidth-common", features = ["user"] }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
crossterm = "0.29"
env_logger = "0.11"
libc = "0.2"
log = "0.4"
ratatui = "0.30"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = [
    "macros",
    "rt-multi-thread",
    "signal",
    "sync",
    "time",
] }
toml = "1"

[build-dependencies]
aya-build = "0.2"
anyhow = "1"
cargo_metadata = "0.23"

[[bin]]
name = "vm-bandwidth-monitor"
path = "src/main.rs"
