[workspace]
members = ["vm-bandwidth", "vm-bandwidth-common", "vm-bandwidth-core", "vm-bandwidth-ebpf"]
resolver = "2"
default-members = ["vm-bandwidth", "vm-bandwidth-common", "vm-bandwidth-core"]

[workspace.package]
version = "0.7.0"
edition = "2021"

[profile.release.package.vm-bandwidth-ebpf]
debug = 2
codegen-units = 1
