[package]
name = "vm-bandwidth-ebpf"
version.workspace = true
edition.workspace = true
license = "GPL-2.0-only"

[dependencies]
aya-ebpf = "0.2"
network-types = "0.2"
vm-bandwidth-common = { path = "../vm-bandwidth-common" }

[build-dependencies]
which = { version = "8", default-features = false, features = ["real-sys"] }

[[bin]]
name = "vm-bandwidth"
path = "src/main.rs"
